refactor: redesigning the readme for shell script
Auto-Devs-sh/devops-playground pull request #15
Opened 2021-03-11 23:51 UTC by bruno0199

2021-03-11 23:52 UTC, guilhermegules requested changes

2021-03-11 23:52 UTC, guilhermegules commented on README.md
> -- 4: Subir 4 VMs conceito de cluster e provisionando com Shell Script.
Why remove this link and don't remove the 3?

2021-03-11 23:55 UTC, guilhermegules commented
Please link the issue on the Pull request too

2021-03-11 23:55 UTC, bruno0199 commented on README.md
> -- 4: Subir 4 VMs conceito de cluster e provisionando com Shell Script.
Pq vamos fazer esse projeto no repositório de vagrant, acho que ficaria redundante não?

2021-03-12 00:13 UTC, guilhermegules commented on README.md
> -- 4: Subir 4 VMs conceito de cluster e provisionando com Shell Script.
então acho que tu pode remover o três também não?

2021-03-12 00:26 UTC, closed without merging